# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a88be840884a8fafd759fb7720132de38d3c25d35de7aa6cff357eefa8cd85bea800f5581a948c418dc4c0afe41d8c4fe982ae4334b1b26406f5512a89677d1c

test:
  secret_key_base: ce1214a649fd16351272edc60b811d71d2594c9763a1a22b7f23944225ba4ddb6be3d778c2060f8583a075c71d14a381c116798c635298e8fc96194e0b2f24bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
